[package]
name = "kona-mpt"
description = "Utilities for interacting with and iterating through a merkle patricia trie"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
# workspace
anyhow.workspace = true
tracing.workspace = true
alloy-primitives = { workspace = true, features = ["rlp"] }
alloy-rlp.workspace = true
alloy-consensus.workspace = true
revm.workspace = true

# External
alloy-trie = { version = "0.4.1", default-features = false }
smallvec = "1.13"

[dev-dependencies]
alloy-consensus.workspace = true
tokio = { version = "1.36.0", features = ["full"] }
alloy-provider = { git = "https://github.com/alloy-rs/alloy", rev = "e3f2f07" }
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", rev = "e3f2f07" }
alloy-transport-http = { git = "https://github.com/alloy-rs/alloy", rev = "e3f2f07" }
reqwest = "0.12"
tracing-subscriber = "0.3.18"
futures = { version = "0.3.30", default-features = false }
