[package]
name = "kona-mpt"
description = "Utilities for interacting with and iterating through a merkle patricia trie"
version = "0.0.3"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
# workspace
anyhow.workspace = true
tracing.workspace = true
alloy-primitives = { workspace = true, features = ["rlp"] }
alloy-rlp.workspace = true
alloy-consensus.workspace = true
revm.workspace = true

# External
alloy-trie = { version = "0.4.1", default-features = false }

[dev-dependencies]
alloy-consensus.workspace = true
tokio = { version = "1.38.0", features = ["full"] }
alloy-provider = { version = "0.2" }
alloy-rpc-types = { version = "0.2" }
alloy-transport-http = { version = "0.2" }
reqwest = "0.12.4"
tracing-subscriber = "0.3.18"
futures = { version = "0.3.30", default-features = false }

proptest = "1.4"
rand = "0.8.5"
criterion = { version = "0.5.1", features = ["html_reports"] }
pprof = { version = "0.13.0", features = ["criterion", "flamegraph", "frame-pointer"] } 

[[bench]]
name = "trie_node"
harness = false
