[package]
name = "kona-host"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
exclude.workspace = true

[dependencies]
# workspace
anyhow.workspace = true
tracing.workspace = true
alloy-primitives = { workspace = true, features = ["serde"] }

# local
kona-common = { path = "../../crates/common", version = "0.0.1" }
kona-preimage = { path = "../../crates/preimage", version = "0.0.1" }

# external
alloy-provider = { git = "https://github.com/alloy-rs/alloy", rev = "e3f2f07" } 
alloy-transport-http = { git = "https://github.com/alloy-rs/alloy", rev = "e3f2f07" } 
alloy-rpc-client = { git = "https://github.com/alloy-rs/alloy", rev = "e3f2f07" } 
reqwest = "0.12"
tokio = { version = "1.37.0", features = ["full"] }
clap = { version = "4.5.4", features = ["derive", "env"] }
serde = { version = "1.0.198", features = ["derive"] }
tracing-subscriber = "0.3.18"
command-fds = "0.3.0"
tempfile = "3.10"
