[package]
name = "kona-host"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
# workspace
anyhow.workspace = true
tracing.workspace = true
alloy-primitives = { workspace = true, features = ["serde"] }
revm = { workspace = true, features = ["std", "c-kzg", "secp256k1", "portable", "blst"] }
alloy-eips.workspace = true
alloy-consensus.workspace = true
alloy-rlp.workspace = true
async-trait.workspace = true

# local
kona-client = { path = "../client", version = "0.1.0" }
kona-common = { path = "../../crates/common", version = "0.0.3" }
kona-preimage = { path = "../../crates/preimage", version = "0.0.3" }
kona-mpt = { path = "../../crates/mpt", version = "0.0.3" }
kona-derive = { path = "../../crates/derive", version = "0.0.3", features = ["online"] }

# external
alloy-provider = { version = "0.2" } 
alloy-transport-http = { version = "0.2" } 
alloy-rpc-client = { version = "0.2" } 
alloy-rpc-types = { version = "0.2" } 
reqwest = "0.12"
tokio = { version = "1.37.0", features = ["full"] }
futures = "0.3"
clap = { version = "4.5.4", features = ["derive", "env"] }
serde = { version = "1.0.198", features = ["derive"] }
tracing-subscriber = "0.3.18"
command-fds = { version = "0.3", features = ["tokio"] }
os_pipe = "1.2.1"
