[package]
name = "kona-derive"
description = "A no_std derivation pipeline implementation for the OP Stack"
version = "0.0.2"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
# Alloy
alloy-eips.workspace = true
alloy-rlp = { workspace = true, features = ["derive"] }
alloy-consensus = { workspace = true, features = ["k256"] }
alloy-primitives = { workspace = true, features = ["rlp", "k256"] }
op-alloy-consensus = { workspace = true, features = ["k256"] }

# General
hashbrown.workspace = true
unsigned-varint.workspace = true
miniz_oxide.workspace = true
brotli.workspace = true
alloc-no-stdlib.workspace = true
anyhow.workspace = true
tracing.workspace = true
async-trait.workspace = true

# Workspace
kona-primitives.workspace = true

# `serde` feature dependencies
serde = { workspace = true, optional = true }

# `online` feature dependencies
lru = { workspace = true, optional = true }
alloy-transport = { workspace = true, optional = true }
alloy-provider = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }

# `metrics` feature dependencies
lazy_static = { workspace = true, optional = true }
prometheus = { workspace = true, optional = true }

# `test-utils` feature dependencies
spin = { workspace = true, optional = true }
alloy-rpc-client = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
alloy-node-bindings = { workspace = true, optional = true }
alloy-transport-http = { workspace = true, optional = true } 

[dev-dependencies]
tokio.workspace = true
proptest.workspace = true
tracing-subscriber.workspace = true
alloy-node-bindings.workspace = true
serde_json.workspace = true

[features]
default = ["serde"]
serde = [
  "dep:serde",
  "kona-primitives/serde",
  "alloy-primitives/serde",
  "alloy-consensus/serde",
  "op-alloy-consensus/serde"
]
metrics = ["dep:prometheus", "dep:lazy_static"]
online = [
  "dep:alloy-provider",
  "dep:alloy-transport",
  "dep:reqwest",
  "dep:lru",
  "alloy-provider/reqwest",
  "alloy-consensus/serde",
  "kona-primitives/online",
  "kona-primitives/serde",
]
test-utils = [
  "dep:spin",
  "dep:alloy-transport-http",
  "dep:alloy-node-bindings",
  "dep:tracing-subscriber",
  "dep:alloy-rpc-client",
  "alloy-transport-http/reqwest"
]
