[package]
name = "kona-derive"
description = "A no_std derivation pipeline implementation for the OP Stack"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
# Workspace Alloy Dependencies
alloy-consensus.workspace = true
alloy-primitives = { workspace = true, features = ["rlp"] }
alloy-rlp = { workspace = true, features = ["derive"] }
alloy-eips.workspace = true
op-alloy-consensus.workspace = true

# Other Workspace Dependencies
lru.workspace = true
spin.workspace = true
anyhow.workspace = true
tracing.workspace = true
async-trait.workspace = true
revm = { workspace = true, optional = true }

# Local
kona-primitives = { path = "../primitives", version = "0.0.1" }

# External
alloy-sol-types = { version = "0.7.6", default-features = false }
hashbrown = "0.14.5"
unsigned-varint = "0.8.0"
miniz_oxide = "0.7.3"
brotli = { version = "6.0.0", default-features = false }
alloc-no-stdlib = "2.0.4"
alloc-stdlib = "0.2.2"

# `serde` feature dependencies
serde = { version = "1.0.203", default-features = false, features = ["derive"], optional = true }

# `online` feature dependencies
c-kzg = { version = "1.0.2", default-features = false, optional = true }
sha2 = { version = "0.10.8", default-features = false, optional = true }
alloy-transport = { git = "https://github.com/alloy-rs/alloy", rev = "cb95183", default-features = false, optional = true }
alloy-provider = { git = "https://github.com/alloy-rs/alloy", rev = "cb95183", default-features = false, optional = true }
alloy-transport-http = { git = "https://github.com/alloy-rs/alloy", rev = "cb95183", optional = true } 
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", rev = "cb95183", default-features = false, optional = true }
serde_json = { version = "1.0.94", default-features = false, optional = true }
reqwest = { version = "0.12.4", default-features = false, optional = true }

# `test-utils` feature dependencies
alloy-node-bindings = { git = "https://github.com/alloy-rs/alloy", rev = "cb95183", default-features = false, optional = true }
tracing-subscriber = { version = "0.3.18", optional = true }
alloy-rpc-client = { git = "https://github.com/alloy-rs/alloy", rev = "cb95183", default-features = false, optional = true }

[dev-dependencies]
tokio = { version = "1.38", features = ["full"] }
proptest = "1.4.0"
tracing-subscriber = "0.3.18"
alloy-node-bindings = { git = "https://github.com/alloy-rs/alloy", rev = "cb95183", default-features = false }
alloy-rpc-client = { git = "https://github.com/alloy-rs/alloy", rev = "cb95183", default-features = false }
serde_json = { version = "1.0.117", default-features = false }

[features]
default = ["serde", "k256"]
serde = [
  "dep:serde",
  "kona-primitives/serde",
  "alloy-primitives/serde",
  "alloy-consensus/serde",
  "op-alloy-consensus/serde"
]
k256 = ["alloy-primitives/k256", "alloy-consensus/k256", "op-alloy-consensus/k256"]
online = [
  "dep:serde_json",
  "dep:revm",
  "dep:c-kzg",
  "dep:sha2",
  "dep:alloy-provider",
  "dep:alloy-rpc-types",
  "dep:alloy-transport",
  "dep:alloy-transport-http",
  "dep:reqwest",
  "alloy-provider/reqwest",
  "alloy-rpc-client/reqwest",
  "alloy-transport-http/reqwest",
  "alloy-consensus/serde",
  "c-kzg/serde",
  "revm/serde",
  "revm/c-kzg",
]
test-utils = ["dep:alloy-node-bindings", "dep:tracing-subscriber", "dep:alloy-rpc-client"]
