[package]
name = "kona-primitives"
description = "Primitive types for kona crates"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
alloy-consensus.workspace = true
alloy-rlp = { workspace = true, features = ["derive"] }
alloy-primitives = { workspace = true, features = ["rlp"] }
alloy-eips.workspace = true
op-alloy-consensus.workspace = true

# Superchain Registry
# superchain-primitives = { version = "0.2", default-features = false }
superchain-primitives = { git = "https://github.com/ethereum-optimism/superchain-registry", branch = "refcell/rust-granite", default-features = false }

# Alloy Types
alloy-sol-types = { version = "0.7.6", default-features = false }

# `serde` feature dependencies
serde = { version = "1.0.203", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
serde_json = { version = "1.0.117", default-features = false }

[features]
default = ["serde"]
serde = ["dep:serde", "superchain-primitives/serde"]
