[package]
name = "kona-client"
version = "0.1.0"
publish = false
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# Workspace
kona-mpt.workspace = true
kona-common.workspace = true
kona-derive.workspace = true
kona-preimage.workspace = true
kona-executor.workspace = true
kona-common-proc.workspace = true

# Alloy
alloy-rlp.workspace = true
alloy-eips.workspace = true
alloy-consensus.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true

# Op Alloy
op-alloy-protocol.workspace = true
op-alloy-consensus.workspace = true
op-alloy-rpc-types-engine.workspace = true
op-alloy-genesis = { workspace = true, features = ["serde"] }

# Revm
revm.workspace = true

# General
lru.workspace = true
spin.workspace = true
serde.workspace = true
cfg-if.workspace = true
anyhow.workspace = true
tracing.workspace = true
serde_json.workspace = true
async-trait.workspace = true
derive_more = { workspace = true, features = ["full"] }

# `tracing-subscriber` feature dependencies
tracing-subscriber = { workspace = true, optional = true, features = ["fmt"] }

[features]
tracing-subscriber = ["dep:tracing-subscriber"]

[[bin]]
name = "kona"
path = "src/kona.rs"
