[package]
name = "kona-client"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
# workspace
cfg-if.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-rlp.workspace = true
alloy-eips.workspace = true
op-alloy-consensus.workspace = true
anyhow.workspace = true
lru.workspace = true
spin.workspace = true
async-trait.workspace = true
tracing.workspace = true
revm.workspace = true

# local
kona-common = { path = "../../crates/common", version = "0.0.3" }
kona-common-proc = { path = "../../crates/common-proc", version = "0.0.3" }
kona-preimage = { path = "../../crates/preimage", version = "0.0.3" }
kona-primitives = { path = "../../crates/primitives", version = "0.0.2" }
kona-mpt = { path = "../../crates/mpt", version = "0.0.3" }
kona-derive = { path = "../../crates/derive", default-features = false, version = "0.0.3" }
kona-executor = { path = "../../crates/executor", version = "0.0.2" }

# external
tracing-subscriber = { version = "0.3.18", optional = true }

[dev-dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.117"

[features]
tracing-subscriber = ["dep:tracing-subscriber"]

[[bin]]
name = "kona"
path = "src/kona.rs"
