[package]
name = "kona-preimage"
description = "Bindings and types for interacting with the PreimageOracle ABI"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
# workspace
anyhow.workspace = true
cfg-if.workspace = true
tracing.workspace = true
alloy-primitives.workspace = true

# local
kona-common = { path = "../common", version = "0.0.1" }

[dev-dependencies]
tokio = { version = "1.36.0", features = ["full"] }
tempfile = "3.10.0"
