[book]
authors = ["clabby"]
language = "en"
multilingual = false
src = "src"
title = "The Kona Book"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.template]

[output.html]
default-theme = "ferra"
preferred-dark-theme = "ferra"
git-repository-url = "https://github.com/anton-rs/kona"
edit-url-template = "https://github.com/anton-rs/kona/edit/main/book/{path}"
additional-css = ["custom.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
