name: Update the monorepo pin commit

on:
  schedule:
    - cron:  '30 5 */2 * *'
  workflow_dispatch:

jobs:
  monorepo-pin:
    name: Update the monorepo pinned commit
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT_TOKEN }}
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@stable
      - name: Update Monorepo Commit 
        run: just update-monorepo
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: Update Monorepo Commit
          signoff: false
          branch: bot/update-monorepo
          base: main
          delete-branch: true
          title: '[BOT] Update Monorepo'
          body: |
            ### Description
            
            Automated PR to update the monorepo commit.
          labels: |
            A-ci
            C-bot
          assignees: refcell
          draft: false
